import api from '@/lib/api';
import { OrderStatus, PaymentStatus } from '@/types/order';
import { DeliveryOption } from '@/types';

interface TestOrderData {
    customer_name: string;
    customer_phone: string;
    customer_email: string;
    cake_size: string;
    flavor: string;
    price: number;
}

const FIRST_NAMES = ['Maria', 'Jose', 'Ana', 'Luis', 'Sofia', 'Carlos', 'Isabella', 'Miguel', 'Camila', 'Juan'];
const LAST_NAMES = ['Garcia', 'Rodriguez', 'Hernandez', 'Martinez', 'Lopez', 'Gonzalez', 'Perez', 'Sanchez', 'Ramirez', 'Torres'];
const CAKE_SIZES = ['6" (8-10 people)', '8" (15-20 people)', '10" (25-30 people)', '12" (35-40 people)', '1/4 Sheet', '1/2 Sheet'];
const FLAVORS = ['Tres Leches', 'Vanilla', 'Chocolate', 'Mocha', 'Red Velvet', 'Strawberry', 'Carrot'];

const generateRandomItem = <T>(array: T[]): T => array[Math.floor(Math.random() * array.length)];

const generateOrderData = (): TestOrderData => {
    const firstName = generateRandomItem(FIRST_NAMES);
    const lastName = generateRandomItem(LAST_NAMES);

    return {
        customer_name: `${firstName} ${lastName}`,
        customer_phone: `(610) ${Math.floor(Math.random() * 900) + 100}-${Math.floor(Math.random() * 9000) + 1000}`,
        customer_email: `${firstName.toLowerCase()}.${lastName.toLowerCase()}@example.com`,
        cake_size: generateRandomItem(CAKE_SIZES),
        flavor: generateRandomItem(FLAVORS),
        price: Math.floor(Math.random() * 200) + 50,
    };
};

export const generateTestOrders = async (count: number = 10) => {
    const orders = [];
    const today = new Date();

    console.log(`Generating ${count} test orders...`);

    for (let i = 0; i < count; i++) {
        const data = generateOrderData();
        const isDelivery = Math.random() > 0.7; // 30% delivery
        const status: OrderStatus = generateRandomItem(['pending', 'confirmed', 'in_progress', 'ready', 'completed']);

        // Ensure first 3 orders are for TODAY so they show up immediately on the dashboard
        const dateNeeded = new Date(today);
        if (i < 3) {
            // keep today
        } else {
            // Spread others over next 7 days
            dateNeeded.setDate(today.getDate() + Math.floor(Math.random() * 7));
        }

        const orderPayload = {
            order_number: `ORD-TEST-${Math.floor(Math.random() * 10000)}`,
            customer_name: data.customer_name,
            customer_phone: data.customer_phone,
            customer_email: data.customer_email,
            customer_language: Math.random() > 0.5 ? 'es' : 'en',

            status: status,
            payment_status: 'paid',

            date_needed: dateNeeded.toISOString().split('T')[0],
            time_needed: `${Math.floor(Math.random() * 10 + 9)}:00`, // 9am - 7pm

            cake_size: data.cake_size,
            filling: data.flavor,
            theme: 'Test Order Theme',
            special_instructions: 'Generated by Test Tool',

            delivery_option: isDelivery ? 'delivery' : 'pickup',
            delivery_address: isDelivery ? '123 Test St, Norristown, PA' : undefined,

            total_amount: data.price,
            created_at: new Date().toISOString()
        };

        try {
            const result = await api.createOrder(orderPayload);
            orders.push(result);
        } catch (error) {
            console.error('Failed to create test order', error);
        }
    }

    return orders;
};
