
-- Insert 5 Valid "Paid" Test Orders
-- Run this in Supabase SQL Editor to populate your dashboard

INSERT INTO orders (
  order_number, 
  customer_name, 
  customer_phone, 
  customer_email, 
  date_needed, 
  time_needed, 
  cake_size, 
  filling, 
  total_amount, 
  status, 
  payment_status, 
  stripe_payment_id, 
  delivery_option, 
  created_at
) VALUES
(
  'RO-8001', 
  'Veronica Real Test', 
  '555-0801', 
  'test1@example.com', 
  CURRENT_DATE, 
  '12:00:00', 
  '10 inch Round', 
  'Tres Leches', 
  65.00, 
  'pending', 
  'paid', 
  'pi_real_db_test_1', 
  'pickup', 
  NOW()
),
(
  'RO-8002', 
  'Jorge Payment', 
  '555-0802', 
  'test2@example.com', 
  CURRENT_DATE, 
  '14:00:00', 
  'Half Sheet', 
  'Chocolate', 
  85.00, 
  'confirmed', 
  'paid', 
  'pi_real_db_test_2', 
  'delivery', 
  NOW()
),
(
  'RO-8003', 
  'Isabella Verified', 
  '555-0803', 
  'test3@example.com', 
  CURRENT_DATE + 1, 
  '10:00:00', 
  '8 inch Round', 
  'Mocha', 
  45.00, 
  'in_progress', 
  'paid', 
  'pi_real_db_test_3', 
  'pickup', 
  NOW()
),
(
  'RO-8004', 
  'Team Lunch', 
  '555-0804', 
  'test4@example.com', 
  CURRENT_DATE + 1, 
  '13:00:00', 
  'Full Sheet', 
  'Vanilla', 
  120.00, 
  'ready', 
  'paid', 
  'pi_real_db_test_4', 
  'delivery', 
  NOW()
),
(
  'RO-8005', 
  'Birthday Surprise', 
  '555-0805', 
  'test5@example.com', 
  CURRENT_DATE + 2, 
  '15:00:00', 
  'Cupcakes (24)', 
  'Red Velvet', 
  55.00, 
  'pending', 
  'paid', 
  'pi_real_db_test_5', 
  'pickup', 
  NOW()
);
